---
title: "CNV dynamics"
author: "Grace Avecilla ga824"
date: "9/26/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is the code to generate figures about CNV dynamics from aggregated flow cyto data.

```{r Load libs + data}

###To get libraries from BioConductor.  This only needs to be run the first time
#source("http://bioconductor.org/biocLite.R")
#biocLite("ggcyto")
#biocLite("tidyverse")

#Load libraries
library(ggcyto)
library(tidyverse)
library(ggjoy)



#working directory
dir = '.'

#file location
path.data = "/Users/Brandt/Google Drive/MiniStatRun_10_2018/"
#path.data = "/Users/nathanbrandt/Google Drive/MiniStatRun_10_2018/"
#list.folders <- c("LTEE_mCitrine_GAP1_Variants_T00", "LTEE_mCitrine_GAP1_Variants_T06", "LTEE_mCitrine_GAP1_Variants_T07", "LTEE_mCitrine_GAP1_Variants_T08.3", "LTEE_mCitrine_GAP1_Variants_T11.1", "LTEE_mCitrine_GAP1_Variants_T11.2", "LTEE_mCitrine_GAP1_Variants_T13.1", "LTEE_mCitrine_GAP1_Variants_T13.2", "LTEE_mCitrine_GAP1_Variants_T14", "LTEE_mCitrine_GAP1_Variants_T15", "LTEE_mCitrine_GAP1_Variants_T18", "LTEE_mCitrine_GAP1_Variants_T22", "LTEE_mCitrine_GAP1_Variants_T25", "LTEE_mCitrine_GAP1_Variants_T27", "LTEE_mCitrine_GAP1_Variants_T29", "LTEE_mCitrine_GAP1_Variants_T34")

list.folders <- c("LTEE_mCitrine_GAP1_Variants_T00", "LTEE_mCitrine_GAP1_Variants_T06", "LTEE_mCitrine_GAP1_Variants_T11.1", "LTEE_mCitrine_GAP1_Variants_T18", "LTEE_mCitrine_GAP1_Variants_T22", "LTEE_mCitrine_GAP1_Variants_T25", "LTEE_mCitrine_GAP1_Variants_T27", "LTEE_mCitrine_GAP1_Variants_T29", "LTEE_mCitrine_GAP1_Variants_T34")


#timepoint <- c(0, 24, 28, 32, 44, 45, 52, 53, 56, 60, 72, 88, 100, 108, 116, 136)

timepoint <- c(0, 24, 44, 72, 136)

date <- '2019-01-13'

data <- read_csv(paste(path.data,list.folders[1],"_prop_",date,".csv", sep=""))
data <- data %>% add_column(TIMEPOINT=timepoint[1]) %>% select(-SAMPLE)


for(i in 2:length(list.folders)){
  data.temp <- read_csv(paste(path.data,list.folders[i],"_prop_",date,".csv", sep=""))
  
  data<- bind_rows(data, data.temp %>% add_column(TIMEPOINT=timepoint[i]) %>% select(-SAMPLE))
}

#Load data frame
load(paste(path.data,list.folders[1],"_df_",date,".Rdata",sep=""))
data2 <- cbind(filtered.data, TIMEPOINT=timepoint[1])
for(i in 2:length(list.folders)) {
  load(paste(path.data,list.folders[i],"_df_",date,".Rdata",sep=""))
  data2.temp <- cbind(filtered.data, TIMEPOINT=timepoint[i])
  
  data2 <- rbind(data2, data2.temp)
}

#Data located here:
#alldata_unmasked <- read.csv("DataOut_11302018.csv")

#Mask out data with fewer than 75000 cells counted
#alldata=alldata_unmasked %>% filter(Cells.counted > 75000)

```

##Plots


```{r Median fl1 over time}
alldata <- data

###PLOT NORMALIZED FLUOR###
myplot <- ggplot(alldata, aes(x=TIMEPOINT,y=(NORMALIZED_GFP_MEDIAN), colour=GENOTYPE)) +
  geom_point() +
  geom_line(aes(linetype=GENOTYPE), size=1.2) +
  scale_y_continuous('Normalized fluorescence signal') +
  #scale_linetype_manual(values=c("twodash", "twodash", "twodash", "solid")) +
  scale_x_continuous("Generations") +
  theme_classic() +
  #scale_color_brewer(palette="Spectral", direction = 1) +
  #scale_color_manual(values = c("#E5F5E0","#C7E9C0", "#A1D99B", "#74C476", "#41AB5D", "#238B45", "#006D2C", "#00441B","#2171B5", "#08519C", "#08306B")) + 
  #facet_grid(Population ~ .) +
  #scale_color_manual(name="Type",values=c("black", "black", "#41ab5d")) +
  guides(colour = guide_legend(override.aes = list(size=2))) + 
  theme(legend.title = element_text(colour="black", size=15, face="bold"), axis.title.y = element_text(face="bold", size=14), axis.text.y = element_text(size=13), axis.title.x = element_text(face="bold", size=16), axis.text.x = element_text(size=15))

myplot #%+% subset(alldata, POPULATION %in% c("Genomic_Architecture_Mutant"))

#median unnormalized fluor#
myplot <- ggplot(alldata, aes(x=TIMEPOINT,y=(FL1_MEDIAN), colour=GENOTYPE)) +
  geom_point() +
  geom_line(aes(linetype=GENOTYPE), size=1.2) +
  #scale_y_continuous('Normalized fluorescence signal', limits=c(0,0.8)) +
  #scale_linetype_manual(values=c("twodash", "twodash", "twodash", "solid")) +
  scale_x_continuous("Generations") +
  theme_classic() +
  #scale_color_brewer(palette="Spectral", direction = 1) +
  #scale_color_manual(values = c("#E5F5E0","#C7E9C0", "#A1D99B", "#74C476", "#41AB5D", "#238B45", "#006D2C", "#00441B","#2171B5", "#08519C", "#08306B")) + 
  #facet_grid(Population ~ .) +
  #scale_color_manual(name="Type",values=c("black", "black", "#41ab5d")) +
  guides(colour = guide_legend(override.aes = list(size=2))) + 
  theme(legend.title = element_text(colour="black", size=15, face="bold"), axis.title.y = element_text(face="bold", size=14), axis.text.y = element_text(size=13), axis.title.x = element_text(face="bold", size=16), axis.text.x = element_text(size=15))

myplot #%+% subset(alldata, Nutrient %in% c("Glutamine"))
```


```{r Proportion CNV cells}
###PLOT PROPORTION OF 2 copy CELLS###
myplot <- ggplot(alldata, aes(x=TIMEPOINT,y=(PopProp_2copy), colour=GENOTYPE)) +
  geom_point() +
  geom_line(size=1.2) +
  scale_y_continuous('Proportion of cells with 2 copies', limits=c(0,1)) +
  #scale_linetype_manual(values=c("twodash", "solid")) +
  scale_x_continuous("Generations") +
  theme_classic() +
  #scale_color_brewer(palette="Spectral", direction = 1) +
  #scale_color_manual(values = c("#E5F5E0","#C7E9C0", "#A1D99B", "#74C476", "#41AB5D", "#238B45", "#006D2C", "#00441B")) + 
  #facet_grid(Population ~ .) +
  #scale_color_manual(name="Type",values=c("black", "black", "#41ab5d")) +
  guides(colour = guide_legend(override.aes = list(size=2))) + 
  theme(legend.title = element_text(colour="black", size=15, face="bold"), axis.title.y = element_text(face="bold", size=14), axis.text.y = element_text(size=13), axis.title.x = element_text(face="bold", size=16), axis.text.x = element_text(size=15))

myplot #%+% subset(alldata, Nutrient %in% c("Glutamine") & Population %in% c("Experimental"))

###PLOT PROPORTION OF 3+ COPY CELLS###
myplot <- ggplot(alldata, aes(x=TIMEPOINT,y=(PopProp_3plus), colour=GENOTYPE)) +
  geom_point() +
  geom_line(size=1.2) +
  scale_y_continuous('Proportion of cells with 3+ copies', limits=c(0,1)) +
  #scale_linetype_manual(values=c("twodash", "solid")) +
  scale_x_continuous("Generations") +
  theme_classic() +
  #scale_color_brewer(palette="Spectral", direction = 1) +
  #scale_color_manual(values = c("#E5F5E0","#C7E9C0", "#A1D99B", "#74C476", "#41AB5D", "#238B45", "#006D2C", "#00441B")) + 
  #facet_grid(Population ~ .) +
  #scale_color_manual(name="Type",values=c("black", "black", "#41ab5d")) +
  guides(colour = guide_legend(override.aes = list(size=2))) + 
  theme(legend.title = element_text(colour="black", size=15, face="bold"), axis.title.y = element_text(face="bold", size=14), axis.text.y = element_text(size=13), axis.title.x = element_text(face="bold", size=16), axis.text.x = element_text(size=15))

myplot# %+% subset(alldata, Nutrient %in% c("Glutamine") & Population %in% c("Experimental"))

```

```{r FSC over time}
####FSC over time####
myplot <- ggplot(alldata, aes(x=TIMEPOINT,y=(FSC_MEDIAN), colour=GENOTYPE)) +
  geom_point() +
  geom_line(size=1.2) +
  scale_y_continuous('FSC') +
  #scale_linetype_manual(values=c("twodash", "solid")) +
  scale_x_continuous("Generations") +
  theme_classic() +
  #scale_color_brewer(palette="Spectral", direction = 1) +
  scale_color_manual(values = c('darkblue','#6baed6','blue', '#a1d99b','#74c476','#41ab5d','#238b45','#006d2c','#00441b', '#08306b', 'black')) + 
  #facet_grid(Population ~ .) +
  #scale_color_manual(name="Type",values=c("black", "black", "#41ab5d")) +
  guides(colour = guide_legend(override.aes = list(size=2))) + 
  theme(legend.title = element_text(colour="black", size=15, face="bold"), axis.title.y = element_text(face="bold", size=14), axis.text.y = element_text(size=13), axis.title.x = element_text(face="bold", size=16), axis.text.x = element_text(size=15))

myplot %+% subset(alldata, Nutrient %in% c("Glutamine"))

####FSC over time without subsetting####
myplot <- ggplot(alldata_unmasked, aes(x=TIMEPOINT,y=(FSC_MEDIAN), colour=GENOTYPE)) +
  geom_point() +
  geom_line(size=1.2) +
  scale_y_continuous('FSC all') +
  #scale_linetype_manual(values=c("twodash", "solid")) +
  scale_x_continuous("Generations") +
  theme_classic() +
  #scale_color_brewer(palette="Spectral", direction = 1) +
  scale_color_manual(values = c('darkblue','#6baed6','blue', '#a1d99b','#74c476','#41ab5d','#238b45','#006d2c','#00441b', '#08306b', 'black')) + 
  #facet_grid(Population ~ .) +
  #scale_color_manual(name="Type",values=c("black", "black", "#41ab5d")) +
  guides(colour = guide_legend(override.aes = list(size=2))) + 
  theme(legend.title = element_text(colour="black", size=15, face="bold"), axis.title.y = element_text(face="bold", size=14), axis.text.y = element_text(size=13), axis.title.x = element_text(face="bold", size=16), axis.text.x = element_text(size=15))

myplot %+% subset(alldata, Nutrient %in% c("Glutamine"))
```
```{r Barplots CNVs over time --- masked and unmasked}
new <- melt(alldata, id.vars = c("Generation", "Sample", "Nutrient"), measure.vars = c("PopProp_0copy","PopProp_1copy","PopProp_2copy","PopProp_3plus"))
new <- data.frame(Generation=as.character(new[,1]), Population=as.character(new[,2]), Nutrient=as.character(new[,3]), variable=as.character(new[,4]), value=as.numeric(new[,5])) 

new$Generation <- factor(new$Generation, levels = unique(alldata$Generation))
new$variable <- factor(new$variable, levels = c("PopProp_3plus", "PopProp_2copy", "PopProp_1copy", "PopProp_0copy"))

theplot <- ggplot(new, aes(Generation, value, fill=variable)) + 
  theme_classic() +
  theme(legend.position = "top", legend.title = element_blank(), axis.title.y = element_text(face="bold", size=14), axis.text.y = element_text(size=13), axis.title.x = element_text(face="bold", size=16)) + 
  geom_bar(colour = "black", position = "fill", stat = "identity", width = 0.9) +
  scale_y_continuous("Proportion", limits=c(0,1)) + 
  scale_fill_manual(values = c('#00441b', '#006d2c', '#a1d99b','#e5f5e0'))

theplot %+% subset(new, Population %in% c("gln_h_bc01"))


theplot %+% subset(new, Nutrient %in% c("Glutamine")) + 
  facet_grid(Population ~ .)


new <- melt(alldata_unmasked, id.vars = c("Generation", "Sample", "Nutrient"), measure.vars = c("PopProp_0copy","PopProp_1copy","PopProp_2copy","PopProp_3plus"))
new <- data.frame(Generation=as.character(new[,1]), Population=as.character(new[,2]), Nutrient=as.character(new[,3]), variable=as.character(new[,4]), value=as.numeric(new[,5])) 

new$Generation <- factor(new$Generation, levels = unique(alldata$Generation))
new$variable <- factor(new$variable, levels = c("PopProp_3plus", "PopProp_2copy", "PopProp_1copy", "PopProp_0copy"))

theplot <- ggplot(new, aes(Generation, value, fill=variable)) + 
  theme_classic() +
  theme(legend.position = "top", legend.title = element_blank(), axis.title.y = element_text(face="bold", size=14), axis.text.y = element_text(size=13), axis.title.x = element_text(face="bold", size=16)) + 
  geom_bar(colour = "black", position = "fill", stat = "identity", width = 0.9) +
  scale_y_continuous("Proportion", limits=c(0,1)) + 
  scale_fill_manual(values = c('#00441b', '#006d2c', '#a1d99b','#e5f5e0'))

theplot %+% subset(new, Population %in% c("gln_h_ctrl2"))


theplot %+% subset(new, Nutrient %in% c("Glutamine")) + 
  facet_grid(Population ~ .)
```

```{r}
#Load data.frame

filtered.data$gens<-factor(data2$TIMEPOINT,levels=unique(data2$TIMEPOINT))

ggplot(data2, aes(x = FL1.A/FSC.A, y = TIMEPOINT, fill = ..x.., height=..density..)) +
  geom_joy_gradient(scale = 1.25, rel_min_height = 0.02) +
  facet_grid(. ~ SAMPLE)
  scale_x_continuous("Normalized Fluorescence (a.u.)", limits=c(0.05,1.4), expand = c(0.01, 0), breaks = c(0.1, 0.7, 1.2)) +
  scale_y_discrete("Generations", expand = c(0.01, 0)) +
  facet_grid(. ~ SAMPLE) + 
  scale_fill_distiller(type = "seq", palette = 5, direction = 1, guide = "colourbar") +
  theme_bw() + 
  theme(text=element_text(size=11),legend.position = 'none', legend.title = element_blank(), axis.title.y = element_text(face="bold", size=12), axis.text.y = element_text(size=10), axis.title.x = element_text(face="bold", size=12), axis.text.x = element_text(size=10))
```